---
repos:
  - repo: https://github.com/talos-systems/conform
    rev: v0.1.0-alpha.26
    hooks:
      - id: conform
        stages:
          - commit-msg
  - repo: https://github.com/dluksza/flutter-analyze-pre-commit
    rev: 0bfdb7415bb2d02794a884bf2b763a92772001eb
    hooks:
      - id: flutter-analyze
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: [
          "--unsafe"
        ]
      - id: detect-aws-credentials
        args: [
            "--allow-missing-credentials"
        ]
      - id: detect-private-key
#      - id: no-commit-to-branch
#        args: [
#            "--branch",
#            "main",
#            "--branch",
#            "next"
#        ]
