---
name: flutter_optimizely
description: Flutter plugin for Optimizely to heck feature flags and feature variables.
version: 1.1.0

homepage: https://github.com/muhlba91/flutter_optimizely
repository: https://github.com/muhlba91/flutter_optimizely
issue_tracker: https://github.com/muhlba91/flutter_optimizely/issues

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  dart_code_metrics: ^4.17.0
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:
  plugin:
    platforms:
      android:
        package: io.niftyside.flutter_optimizely
        pluginClass: FlutterOptimizelyPlugin
      ios:
        pluginClass: FlutterOptimizelyPlugin
