---
name: flutter_optimizely
description: Flutter plugin for Optimizely to heck feature flags and feature variables.
version: 1.3.0

homepage: https://github.com/muhlba91/flutter_optimizely
repository: https://github.com/muhlba91/flutter_optimizely
issue_tracker: https://github.com/muhlba91/flutter_optimizely/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  dart_code_metrics: ^5.7.4
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:
  plugin:
    platforms:
      android:
        package: io.niftyside.flutter_optimizely
        pluginClass: FlutterOptimizelyPlugin
      ios:
        pluginClass: FlutterOptimizelyPlugin
